CREATE DATABASE QUANLYRAPPHIM
GO
CREATE TABLE KHACHHANG
(
	MAKH varchar(5),
	HOTENKH NVARCHAR(50),
	SDTKH VARCHAR(20),
	DIACHIKH NVARCHAR(500),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(5)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
);
GO